plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
            gameDirectory = file('runs/client')
        }
        server {
            server()
            gameDirectory = file('runs/server')
        }
        data {
            data()
            gameDirectory = file('runs/data')
            programArguments.addAll '--mod', project.mod_id, '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version_range : minecraft_version_range,
            neo_form_version        : neo_form_version,
            neoforge_loader_version_range: neoforge_loader_version_range,
            neoforge_version        : neoforge_version,
            mod_id                  : mod_id,
            mod_name                : mod_name,
            mod_license             : mod_license,
            mod_version             : mod_version,
            mod_authors             : mod_author,
            mod_description         : mod_description
    ]
    inputs.properties replaceProperties
    replaceProperties.putIfAbsent('project', project)
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
